# -*- mode: ruby -*-
# vi: set ft=ruby :

# Build a RHEL8 box requiring a valid RHEL subscription to install and config
# snapd.
#
# Requires: 1) Virtualbox
#           2) vagrant-registration plugin
#              https://github.com/projectatomic/adb-vagrant-registration
#              If you need to bypass proxy to install plugin:
#              export no_proxy="$no_proxy,gems.hashicorp.com,rubygems.org"
#
# Author: Justin Cook <jhcook@secnix.com>

# Script to provision post deploy
$pscript = <<-SCRIPT
# Disable SELinux because we don't need it to get in the way
echo "Disable SELinux :'("
sed -i -E 's|^(SELINUX=).*|\1permissive|' /etc/selinux/config
setenforce 0
echo "Install EPEL"
yum install -y \
  https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum upgrade
echo "Install snapd" #, libvirt-devel, virt-top, and libguestfs-tools"
yum install -y snapd #libvirt-devel virt-top libguestfs-tools
echo "Disable firewalld"
systemctl disable firewalld
#echo "Enable libvirtd"
#systemctl enable --now libvirtd
echo "Enable snapd"
systemctl enable --now snapd.socket
# Wait on snap to seed
/usr/bin/snap wait system seed.loaded
ln -s /var/lib/snapd/snap /snap
echo "Install multipass snap"
/usr/bin/snap install multipass
#/usr/bin/snap connect multipass:libvirt
#/snap/bin/multipass set local.driver=libvirt
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "secnix/rhel8"

  # Require the vagrant-registration plugin
  config.vagrant.plugins = "vagrant-registration"

  # Mark SUB_PASSWORD environment variable as sensitive
  config.vagrant.sensitive = ENV['SUB_PASSWORD']

  config.vm.provider "virtualbox" do |v|
    v.memory = 12288
    v.cpus = 4
    # Enable nested virtualization
    v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # Use a public network for access on the network
  #config.vm.network "public_network", use_dhcp_assigned_default_route: true

  if Vagrant.has_plugin?('vagrant-registration')
    config.registration.manager = 'subscription_manager'
    config.registration.force = false
    config.registration.unregister_on_halt = false
    config.registration.username = ENV['SUB_USERNAME']
    config.registration.password = ENV['SUB_PASSWORD']
  end

  # Provision the machine with shell and reboot afterwards
  config.vm.provision "shell", inline: $pscript, reboot: true

end
