# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.extra_args = [ "-tt", ]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["storageattach", :id, 
                  "--storagectl", "SCSI", "--port",
                  "3", "--type", "dvddrive", "--medium", "emptydrive"]
  end

  # https://stackoverflow.com/questions/32437006/using-sed-to-append-lines-to-file-during-vagrant-provisioning
  config.vm.provision "shell", inline: <<-SHELL
    /bin/sed -i '0,/^Defaults\\s/s//Defaults\\t!requiretty\\n&/' /etc/sudoers
  SHELL

  # https://serverfault.com/questions/686000/vagrant-and-mariadb-provision
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y gdm3 tasksel
    tasksel install ubuntu-desktop
    systemctl set-default graphical.target
    systemctl start gdm3
  SHELL
end
