# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

K8SV="1.21.2"
DSHV="1-21-6"

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/centos8"

  config.vagrant.plugins = "vagrant-reload"

  # config.vm.box_check_update = false
  # Kubernetes API
  config.vm.network "forwarded_port", guest_ip: "10.0.2.15", guest: 6443, \
                    host: 6443
  config.vm.network "forwarded_port", guest_ip: "10.0.2.15", guest: 80, \
                    host: 80
  config.vm.network "forwarded_port", guest_ip: "10.0.2.15", guest: 443, \
                    host: 443

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # Customize the amount of memory on the VM:
    vb.memory = "16384"
    vb.cpus = 4
  end

  config.vm.provision "shell" do |sh|
    sh.path = "src/centos8_provision.sh"
    sh.args = "#{K8SV} #{DSHV}"
  end

  # Reboot -- c'est la vie
  config.vm.provision :reload

  config.vm.provision "shell" do |sh|
    sh.path = "src/centos8_postprovision.sh"
  end
end
