# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: Justin Cook <jhcook@gmail.com>

$VB_NAME = "centos7-devstack-bootstrap"

Vagrant.configure(2) do |config|

  config.vm.box = "bis/rhel7"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vbvm|
    vbvm.name = $VB_NAME
    vbvm.customize ['modifyvm', :id, '--name', vbvm.name]
    vbvm.memory = 4096
    vbvm.cpus = 2
  end

  # The guest should have an identifiable hostname
  config.vm.hostname = "centos7-devstack.secnix.com"

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
#  config.vm.network "private_network", ip: "10.2.3.4", nictype: 'virtio', 
#                    adapter: 2, virtualbox__intnet: "devstack"

  # Use tabs!!! There are embedded here docs.

  config.vm.provision "shell", inline: <<-SHELL
	set -x
	set -o errexit
	
	# Install tools needed to create the environment
	yum -y install git

	# Restart networking so changes take effect (Vagrant/RHEL workaround)
	systemctl restart NetworkManager.service &&  systemctl restart network.service || /bin/true

	# Create the user 'stack' and give it unlimited sudo
	adduser stack || /bin/true
	echo "stack ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
	sed -ie 's|Defaults\s\+requiretty|#Defaults\trequiretty|' /etc/sudoers

	su - stack <<-__HACK__
		if [ -d 'devstack' ]
		then
			rm -fr devstack
		fi

		git clone https://git.openstack.org/openstack-dev/devstack #-b stable/mitaka
		cd devstack
	
		cat <<-__EOF__ > local.conf
		[[local|localrc]]
		HOST_IP=10.0.2.15
		ADMIN_PASSWORD=admin
		DATABASE_PASSWORD=admin
		RABBIT_PASSWORD=admin
		SERVICE_PASSWORD=admin
		SERVICE_TOKEN=a682f596-76f3-11e3-b3b2-e716f9080d50
		LOGDAYS=1
		LOGDIR=/home/stack/devstack/log
		LOGFILE=/home/stack/devstack/log/stack.sh.log
		__EOF__
		
	./stack.sh
	__HACK__

	SHELL
end
