# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: Justin Cook <jhcook@gmail.com>

Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "jhcook/centos7-devstack"

  # The guest should have an identifiable hostname
  config.vm.hostname = "centos7-devstack.secnix.com"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Name the vm clever but avoid collisions
    vb.name = "centos7_devstack_#{Time.now.utc.to_i}"

    # Customize the amount of memory and CPU on the VM:
    vb.memory = 4096
    vb.cpus = 2

    # Paravirt the NIC
    vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
  end
end
